CREATE TABLE public.suisit_profiles (
  id SERIAL PRIMARY KEY,
  username TEXT,
  firstname TEXT,
  lastname TEXT,
  photourl TEXT,
  isbot BOOLEAN,
  ispremium BOOLEAN,
  languagecode TEXT,
  balance NUMERIC,
  mininglevel INTEGER,
  energy NUMERIC,
  rewards NUMERIC,
  lastharvesttime BIGINT,
  lastexhaustedtime BIGINT,
  lastenergydepletiontime BIGINT,
  cooldownendtime BIGINT,
  referrerid INTEGER,
  referredplayers INTEGER[],
  lastlogindate TEXT,
  loginstreak INTEGER,
  lastupdated BIGINT,
  walletaddress TEXT UNIQUE NOT NULL,
  jwttoken TEXT,
  usersalt TEXT,
  maxepoch INTEGER,
  email TEXT
);
